<div class="gallery">

  <div class="imageGridPercentage">
    <a href="blog.php?id=6"><div class="tile contone">
      <div class="textWrapper"><h2>3 weeks in - Mayden Academy so far...</h2>
        <div class="content">I have a few minutes on my train ride in and I thought this would be as good a time as any to reflect on my first three weeks at the Mayden Academy.</div>
      </div>
    </div></a>
  <a href="blog.php?id=5"><div class="tile conttwo">
    <div class="textWrapper"><h2>Create a honeycomb with CSS</h2>
      <div class="content">I had a few minutes to have a messaround and practice my CSS.</div>
    </div>
  </div></a>
  <a href="blog.php?id=4"><div class="tile contthree">
    <div class="textWrapper"><h2>Creating the Mayden Academy Logo with pure CSS</h2>
      <div class="content">We have been set a task for this sprint. It was to create the Mayden Academy logo using only CSS and no image tags.</div>
    </div>
    </div></a>
  <a href="blog.php?id=3"><div class="tile contfour">
    <div class="textWrapper"><h2>HTML/CSS - Float left</h2>
      <div class="content">Today we have begun working on HTML and CSS - here is one of the concepts that I found interesting.</div>
    </div>
    </div></a>
  <a href="blog.php?id=2"><div class="tile contfive">
    <div class="textWrapper"><h2>PHP script to display form data in HTML</h2>
      <div class="content">After a quick introduction to PHP arrays - i was interested in writing a quick piece of code that practices array creation.</div>
    </div>
    </div></a>
  <a href="blog.php?id=1"><div class="tile contsix">
    <div class="textWrapper"><h2>Using the lamp stack and intro to databases</h2>
      <div class="content">Here is what we have done today, I am writing this down as a method of revision.</div>
    </div>
  </div></a>

  <a href="blog.php?id=5"><div class="tile contseven">
    <div class="textWrapper"><h2>First week - setting up environment, command line and Git</h2>
      <div class="content">The first week has flown by and I am currently taking stock of what I have learnt this week at the Mayden academy.</div>
    </div>
  </div></a>
    <a href="blog.php?id=5"><div class="tile conteight">
    <div class="textWrapper"><h2>Why do I want to learn to code</h2>
      <div class="content">Of all the skills that a web developer requires, coding was the aspect I was most keen to learn, and here’s why:</div>
    </div>
    </div></a>
    <a href="blog.php?id=5"><div class="tile contnine">
    <div class="textWrapper"><h2>Random Article</h2>
      <div class="content">Dont know which post to view? Click here to view a random article</div>
    </div>
    </div></a>




  </div>

</div>
