<div class="heading">
  <h1 class="title">HTML AND CSS FLOAT LEFT</h1>
  <p class="date">SEP 28, 2015</p>
</div>

<div class="blogcontent">
  <p>Today we have begun working on HTML and CSS - here is one of the concepts that I found interesting. It is how to display elements next to each other without changing the display to inline. It is using float:left
</p>
  <p>Here's my HTML code</p>
  <img src="img/codeshot1.png" />
  <p>This was linked to the following CSS code</p>
  <img src="img/codeshot2.png" />
  <p>And here is the result</p>
  <img src="img/webshot.png" />
  <p>Snazzy!</p>

</div>
