<div class="heading">
  <h1 class="title">PHP SCRIPT TO DISPLAY FORM DATA IN HTML</h1>
  <p class="date">SEP 23, 2015</p>
</div>

<div class="blogcontent">
  <p>After a quick introduction to PHP arrays - i was interested in writing a quick piece of code that practices array creation, assigning new items to that array and then finally recalling them.</p>
  <img src="img/codeshot.jpg" />
  <p>I created a numerical based index array and used an HTML form input to prompt the user to enter a name and email. These bits of data were then put into the POST array and then called upon using the zero index numbering scheme. It is a simple solution and with a little bit of HTML and CSS I was able to build a frontend to display it all in the browser.</p>
  <img src="img/frontendshot.png" />
</div>
