<div class="heading">
  <h1 class="title">3 WEEKS IN - MAYDEN ACADEMY SO FAR...</h1>
  <p class="date">OCT 2, 2015</p>
</div>

<div class="blogcontent">
  <p>I have a few minutes on my train ride in and I thought this would be as good a time as any to reflect on my first three weeks at the Mayden Academy.</p>
  <p>It has absolutely flown by - I currently have that feeling when an event goes incredibly quickly but at the same time cant remember what it was like when I wasn’t here at the academy! As the weeks go on, the 6 of us trainees, are finding ourselves being given more direction and introduced to more complex and technical knowledge. This is exactly what we all want and it is still suprising how much ground we are covering in our short sprints.</p>
  <p>With the expertise already here at Mayden it makes for a great learning environment, allowing us to get as much out of our time in the academy as we want. I am absolutely loving being here and being a part of this process - I would strongly recommend that anyone out there who wants to get into software engineering/web development gets in touch and urges Mayden to run as many of these Academys as possible!</p>
  <p>my train stop is coming up here is a list of my 3 favourite things about the academy so far to finish this post up!</p>
  <p>The enthusiasm to learn that all the academy trainees share, The feeling that I am working towards a career in a brilliant industry, The relaxed atmosphere at Mayden.</p>
  <img src="img/learningjuice.jpg" />
</div>
